### ISSUE TITLE
Does not run on Factorio Stable (1.1.53)

### ISSUE THREAD

**Issue by harag-on-steam** [raiguard/PipeVisualizer#1]
... which in my opinion should be the case for mods on the mod portal if there's no clear warning. Does it actually require a feature from 1.1.55 or would 1.1.53 have sufficed?

It's a little annoying to think "cool, I'll try that" and then it takes a few seconds to realize that the "Install" button is greyed out because of "base >= 1.1.55". And not everyone might make that connection.

**Comment by raiguard** [comment]
It requires a feature that was added in 1.1.54. Specifically `LuaFluidBox::get_fluid_system_id()`, which was added at my request specifically for this mod.

**Comment by harag-on-steam** [comment]
I guess my suggestion then is to put a warning at the top of the description that the mod requires the experimental branch and leave this ticket open until 1.1.55 hits stable.

**Comment by raiguard** [comment]
I'm not really sure it's necessary. As you said, it won't let you download it if you don't have a compatible version, so a warning would be redundant.

**Comment by harag-on-steam** [comment]
You and I understand the meaning of "base >= 1.1.54", not everyone does. But I guess 1.1.55 isn't too far off and people can find this ticket in the meanwhile.

**Comment by raiguard** [comment]
I'll keep this open until 1.1.55 goes stable.

**Comment by CricketBr** [comment]
Thanks! Took me a while to figure out why the Install button was greyed out. Just assumed latest stable would work, didn't actually compare the rev numbers.
