### ISSUE TITLE
Feature request - disable hover-over visualizer when moving faster than XX

### ISSUE THREAD

**Issue by The-Talik** [raiguard/PipeVisualizer#10]
I love this mod!  The hover visualizer takes a moment to show up, which freezes my game and is annoying when I'm flying around.  Would be nice if it disabled itself when I was moving fast.  Or alternatively, maybe have it take a hover of a few ticks before it shows up.

**Comment by raiguard** [comment]
I think I'm going to replace the hover-over visualizer with needing to use a hotkey to show it. Performance can get pretty bad with large networks.

**Comment by The-Talik** [comment]
I had a random idea.  I'm not sure how difficult this would be to implement, but a really smooth operation that would  fix the performance issue you mentioned might be that the pipe visualizer expands by one connection every tick.  So the first tick it shows just what the pipe you are hovering over is connected to, and the next tick would include what all of those are connected to.  Would limit how much work the mod is doing in a single tick, while still feeling very responsive, because people are always going to focus their attention first on what they are hovering over.

Personally, I love this mod, and would love to just keep it always active, if there wasn't the performance issue.

**Comment by jingleheimer-schmidt** [comment]
I would also prefer a staged approach over a hotkey, since there's already a hotkey to turn the highlight-on-hover on/off anyways. I think it would be fun to hover over a pipe and watch as the highlights make their way through the fluid system

**Comment by raiguard** [comment]
Closing in favor of #14. Version 2.0 will feature a hotkey to highlight specific systems, as well as a toggle to auto-highlight on hover. It also propagates over time to reduce the performance impact.
