### ISSUE TITLE
visualizer doesn't update when a new selected entity is part of two fluid networks and one is shared by the previous selected entity

### ISSUE THREAD

**Issue by jingleheimer-schmidt** [raiguard/PipeVisualizer#13]
### Description

I'm not sure what the actual root cause is, but it appears that when a player selected entity changes to another entity that shares a fluid network with the first entity, the visualizer doesn't update any of the other network visualizations that the new entity might be part of

https://user-images.githubusercontent.com/46385945/234670320-180f67cf-3db8-4c5d-975b-94bf5ec23a6b.mp4

**Comment by DoubleThoughtTheProgrammer** [comment]
I can confirm that this also happens for me.

**Comment by raiguard** [comment]
This is no longer relevant because hover-over has been removed.
