### ISSUE TITLE
Feature request: Highlight a single fluid system and keep it active without hovering

### ISSUE THREAD

**Issue by alexbarrett** [raiguard/PipeVisualizer#14]
I use the hover-over pipe visualizer often to trace a single pipe through a factory. A really nice feature for this use case would be to 'lock' the visualization in place so it's not necessary to keep hovering over individual pipe sections during the tracing process. I think this feature could replace the hover interaction entirely because as long as it were bound to a convenient hotkey it's not much more effort to hover and hit a key vs just hovering.

This feature is necessary in addition to the current 'visualize all fluid systems' feature because it would not be limited by range and work in map view.

The [Belt Visualizer](https://mods.factorio.com/mod/belt-visualizer) mod has a feature like this for belts: when a belt is highlighted with H it remains highlighted until the H key is hit again.

**Comment by Nevrai** [comment]
I came here to request this! It would be super useful!

**Comment by raiguard** [comment]
https://github.com/raiguard/PipeVisualizer/assets/3515394/74d16bc0-d0f5-4f7e-9b85-dfee0527cf32

Coming soon(TM)

**Comment by Atria1234** [comment]
Any news on this? Is the branch 2.0 stable enough for testing? Where could I get the new version of flib which goes along with the 2.0 of this mod?

**Comment by raiguard** [comment]
The 2.0 branch is usable, but performance is pretty bad at the moment. You can grab the latest flib by cloning https://github.com/factoriolib/flib to your mods folder.

**Comment by raiguard** [comment]
Implemented in 2.0.
