### ISSUE TITLE
Press h each time?

### ISSUE THREAD

**Issue by Falafelrollo** [raiguard/PipeVisualizer#18]
### Description

before the last update loved the mod just hover a pipe and see the pipe system.
do I use this version wrong or do I have to press h each time now? after each pipe added, after I am done building.

**Comment by Falafelrollo** [comment]
and after i try go back to 1.06 i get crashes each time i move my mouse
![image](https://github.com/raiguard/PipeVisualizer/assets/35108510/e6cb0745-0702-4c4a-b445-eafc0a70dba1)


removing the mod, saving and re adding version 1.06 worked

**Comment by raiguard** [comment]
Yeah, downgrading isn't supported and will cause problems.

The hover-over was removed in favor of the hotkey. With the new systems the hover-over had issues that I couldn't trivially fix and I didn't want to delay the release any longer. In the future I will hopefully add the capability for it to auto-update the visualization as things are built or removed, but that is unfortunately far more difficult than it sounds.

Keep an eye on #16 if you wish.

**Comment by Falafelrollo** [comment]
ok i will wait :) thanks
