### ISSUE TITLE
indistinguishable fluids in some cases

### ISSUE THREAD

**Issue by sakuro** [raiguard/PipeVisualizer#2]
I tried this MOD with my current K2 + BZ mods run. ([Some screenshots](https://imgur.com/a/8pfT3B7))

Are colors of fluids determined automatically?  I feel sulfuric acid(yellow?) and dirty water(orange?) in the third pic difficult to distinguish.

**Comment by raiguard** [comment]
The fluid colors are determined based on the fluid's `base_color`. For this reason, the mod provides the option to color by system in case the fluid colors are too close together.
