### ISSUE TITLE
Show pipe around viepower, not player

### ISSUE THREAD

**Issue by Dorus** [raiguard/PipeVisualizer#22]
When scrolling around the map (in map more, 'm' mode etc.) you quickly leave the area where the pipes are colored, would be nice if this area followed the camera, not the player.

**Comment by raiguard** [comment]
This is unfortunately impossible to fix. The map view is entirely client-side rendering and mods are unable to know where the player is looking.

**Comment by Dorus** [comment]
Never mind, i just discovered i can select a single pipe system with no distance limitations by pressing H. Idk how i missed that but that's all i ever wanted :)
