### ISSUE TITLE
[Crash] Error while running event PipeVisualizer::on_tick (ID 0)

### ISSUE THREAD

**Issue by the-daveman** [raiguard/PipeVisualizer#32]
I wasn't actually performing any actions when the crash took place.
My best guess is that it occurred while performing a mouseover the pipe or fuel tank on the spaceship anchored in an Asteroid Field (SE).

The crash identically matches the screenshot posted in this closed bug, but I am not using logistic tanks (mod), so I don't have a workaround or resolution for this issue. Hopefully it doesn't reproduce. :) 

_Originally posted by @Valoneu in https://github.com/raiguard/PipeVisualizer/issues/29#issuecomment-1879088854_
            
![20240303043102_1](https://user-images.githubusercontent.com/5562517/309550265-200c8656-f6f0-423e-8ebe-d14cadcc0a22.jpg)

**Comment by raiguard** [comment]
Fixed by #28
