### ISSUE TITLE
Not able to connect pipes with same fluid after updating to version 2.2.1

### ISSUE THREAD

**Issue by Atlntssplayer** [raiguard/PipeVisualizer#34]
### Description

I updated a few mods since I last played and noticed that I can't connect pipes containing the same water anymore.
I didn't have this problem before so I suspected it might be one of the updated mods and at first glance only PipeVisualizer has anything to do with pipes and fluids so I deleted it and now I can connect the pipes.
I haven't tried to go back to the previous version of PipeVisualizer but I think I didn't have this problem with that version (2.2.0).

If there is a chance PipeVisualizer might cause this error please take a loot into it.

Thank you

### Reproduction

1. Load save
2. disconnect pipes containing water
3. try to connect them again
4. getting error that "fluid system containing different fluids can't be connected"

**Comment by raiguard** [comment]
There is a 0% chance that Pipe Visualizer is causing this, it doesn't modify fluid systems in any way, it only visualizes their contents.
