### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Falafelrollo** [raiguard/PipeVisualizer#35]
### Description

<img width="383" alt="Screenshot 2024-05-09 091415" src="https://github.com/raiguard/PipeVisualizer/assets/35108510/84c3d034-bb60-4c2c-b028-f4fef0824cf6">

### Reproduction

[FCM May 2024 - MOD AND SETTINGS SYNC.zip](https://github.com/raiguard/PipeVisualizer/files/15258950/FCM.May.2024.-.MOD.AND.SETTINGS.SYNC.zip)
when i hover over the maze chasem
![image](https://github.com/raiguard/PipeVisualizer/assets/35108510/4ad9dbbd-c078-430b-bbfb-0f4f853eaf09)
 and move up and down in my spidertron via wasd the game crashed. did trie it 3-4 times before i posted it here.

**Comment by raiguard** [comment]
That's weird, somehow the overlay background object was destroyed. I can add a check for this and re-create it but I'm concerned about how it happened in the first place.
