### ISSUE TITLE
Map view when overlay is active

### ISSUE THREAD

**Issue by Atraxi** [raiguard/PipeVisualizer#6]
It seems the overlay stays centered on the character, as well as the pre-computed/cached pipe overlays, when opening the map and zooming in a bit and scrolling around.

I can get screenshots or a list of other mods installed if needed.

**Comment by raiguard** [comment]
This is unfixable. There is no way to get the player's position when in the map view.

**Comment by Atraxi** [comment]
Maybe just disable the overlay when opening map mode then?

**Comment by raiguard** [comment]
I'd rather have it partially work on the map then not at all. Sorry I can't fix it - I've wanted to be able to use it on the map as well but there's just no way to make it work.
