### ISSUE TITLE
view not fully darkened in map editor

### ISSUE THREAD

**Issue by DanielKote** [raiguard/PipeVisualizer#7]
When using the pipe visualizer (all) the view darkens to be able to better see the pipes. In map editor it is possible to zoom out further than you can in regular play which results in the darkened view being applied only to a central square as opposed to the entire screen.

It is likely that the same issue happens if taking larger screen shots or when coupled with 'extended zoom out' mods. Not sure if it is possible to set the size of the darkened area based on the current view, but perhaps just increasing it to cover the entire view when using map editor?

See screenshot for example.
![screenshot-tick-43509725](https://user-images.githubusercontent.com/93489857/157286939-142d303b-9a97-4de0-a0fe-f66117b34349.png)

**Comment by raiguard** [comment]
This is intentional. Making the overlay any larger will make performance even worse. The square is just big enough to cover the max zoom when you're playing normally.

Reading the player's current zoom level is actually impossible with the Factorio API.
