### ISSUE TITLE
Crash to menu when hovering over pipes connected to multiple 'Fluid burning heat source' (Seablock 0.5.10)

### ISSUE THREAD

**Issue by garethwilson** [raiguard/PipeVisualizer#8]
Fluid burning heat sources allow for fluids to flow through them to other heat sources. Once I have connected a pipe to one of the heat sources, hovering over any piece of pipe connected to that fluid system causes a crash.

Turning on the always on visualizer works, and the fluid visualization stops at the first heat source

Hover visualization works as expected if only a single heat source is connected. 

Error Message:

```
Error while running event PipeVisualizer::on_selected_entity_changed (ID 53)
'index': real number expected got string.
stack traceback:
	[C]: in function 'get_fluid_system_id'
	__PipeVisualizer__/control.lua:53: in function 'walk_fluid_system'
	__PipeVisualizer__/control.lua:171: in function <__PipeVisualizer__/control.lua:142>
```

**Comment by raiguard** [comment]
Please provide a save file I can sync mods with and exact reproduction steps.

**Comment by garethwilson** [comment]
[pipe-repro.zip](https://github.com/raiguard/Factorio-PipeVisualizer/files/8240956/pipe-repro.zip)

Save file attached. That was created with Factorio version 1.1.56.

Just hover over either the large tank or the pipe connecting to the heat source

**Comment by garethwilson** [comment]
I've just updated to 1.0.2 and it looks like I can now hover over the pipe entities.

However, hovering over the heat source still causes a crash:

```
Error while running event PipeVisualizer::on_selected_entity_changed (ID 53)
'index': real number expected got string.
stack traceback:
	[C]: in function 'get_fluid_system_id'
	__PipeVisualizer__/control.lua:168: in function <__PipeVisualizer__/control.lua:143>
```
